const escapeHtml = (value: string) =>
    value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/\"/g, "&quot;")
        .replace(/'/g, "&#039;");

const toDate = (value?: string) => {
    if (!value) return null;
    const normalized = value.includes("T") ? value : `${value}T00:00:00`;
    const parsed = new Date(normalized);
    if (Number.isNaN(parsed.getTime())) return null;
    return parsed;
};

const formatDate = (value?: string) => {
    const parsed = toDate(value);
    if (!parsed) return value || "";
    return parsed.toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
    });
};

const formatDateTime = (value?: string) => {
    const parsed = toDate(value);
    if (!parsed) return value || "";
    return parsed.toLocaleString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
};

const formatPercent = (value: number) => `${value.toFixed(1)}%`;

const baseStyles = `
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica', 'Arial', sans-serif; color: #0f172a; margin: 0; padding: 28px; background: #f8fafc; }
  h1, h2, h3, p { margin: 0; }
  .page { background: #ffffff; border-radius: 16px; padding: 28px; box-shadow: 0 10px 24px rgba(15, 23, 42, 0.08); }
  .header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; border-bottom: 1px solid #e2e8f0; padding-bottom: 16px; }
  .title { font-size: 24px; font-weight: 700; color: #0f172a; }
  .subtitle { font-size: 12px; color: #64748b; margin-top: 4px; }
  .meta { font-size: 11px; color: #475569; text-align: right; }
  .meta div { margin-bottom: 4px; }
  .section { margin-top: 20px; }
  .section-title { font-size: 14px; font-weight: 700; color: #1e293b; margin-bottom: 8px; }
  .card-row { display: flex; gap: 12px; flex-wrap: wrap; }
  .stat-card { flex: 1 1 150px; background: #f1f5f9; border-radius: 12px; padding: 12px; }
  .stat-value { font-size: 20px; font-weight: 700; color: #0f172a; }
  .stat-label { font-size: 11px; color: #64748b; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { text-align: left; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: #475569; background: #f8fafc; padding: 10px; border-bottom: 1px solid #e2e8f0; }
  td { font-size: 12px; color: #1e293b; padding: 10px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
  .badge { display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 10px; font-weight: 700; }
  .badge-success { background: #dcfce7; color: #15803d; }
  .badge-warning { background: #fef9c3; color: #a16207; }
  .badge-danger { background: #fee2e2; color: #b91c1c; }
  .badge-neutral { background: #e2e8f0; color: #475569; }
  .footer { margin-top: 24px; font-size: 10px; color: #94a3b8; text-align: center; }
</style>
`;

const buildDocument = (title: string, subtitle: string, meta: Record<string, string>, content: string) => {
    const metaHtml = Object.entries(meta)
        .filter(([, value]) => value)
        .map(([label, value]) => `<div><strong>${escapeHtml(label)}:</strong> ${escapeHtml(value)}</div>`)
        .join("");

    return `<!DOCTYPE html><html><head>${baseStyles}</head><body><div class="page">` +
        `<div class="header"><div><div class="title">${escapeHtml(title)}</div><div class="subtitle">${escapeHtml(subtitle)}</div></div>` +
        `<div class="meta">${metaHtml}</div></div>` +
        `${content}` +
        `<div class="footer">Generated by Teachora • ${escapeHtml(new Date().toLocaleString())}</div>` +
        `</div></body></html>`;
};

const buildTable = (headers: string[], rows: string[][]) => {
    const headHtml = headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("");
    const rowHtml = rows
        .map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`)
        .join("");
    return `<table><thead><tr>${headHtml}</tr></thead><tbody>${rowHtml}</tbody></table>`;
};

const statusBadge = (status: string) => {
    const normalized = status.toUpperCase();
    if (normalized === "APPROVED" || normalized === "PRESENT") {
        return `<span class="badge badge-success">${escapeHtml(status)}</span>`;
    }
    if (normalized === "PENDING") {
        return `<span class="badge badge-warning">${escapeHtml(status)}</span>`;
    }
    if (normalized === "REJECTED" || normalized === "ABSENT" || normalized === "CANCELLED") {
        return `<span class="badge badge-danger">${escapeHtml(status)}</span>`;
    }
    return `<span class="badge badge-neutral">${escapeHtml(status)}</span>`;
};

export const pdfTemplates = {
    attendanceHistoryReport: ({
        studentName,
        institutionName,
        records,
        stats,
    }: {
        studentName: string;
        institutionName?: string;
        records: {
            date: string;
            subject: string;
            className: string;
            teacher: string;
            status: string;
        }[];
        stats: { total: number; present: number; absent: number };
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Summary</div>
            <div class="card-row">
              <div class="stat-card"><div class="stat-value">${stats.total}</div><div class="stat-label">Total Sessions</div></div>
              <div class="stat-card"><div class="stat-value">${stats.present}</div><div class="stat-label">Present</div></div>
              <div class="stat-card"><div class="stat-value">${stats.absent}</div><div class="stat-label">Absent</div></div>
            </div>
          </div>
          <div class="section">
            <div class="section-title">Attendance Records</div>
            ${buildTable(
                ["Date", "Subject", "Class", "Teacher", "Status"],
                records.map((r) => [
                    escapeHtml(formatDate(r.date)),
                    escapeHtml(r.subject),
                    escapeHtml(r.className),
                    escapeHtml(r.teacher),
                    statusBadge(r.status),
                ])
            )}
          </div>
        `;

        return buildDocument(
            "Attendance Report",
            studentName,
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    resultsReport: ({
        studentName,
        institutionName,
        results,
    }: {
        studentName: string;
        institutionName?: string;
        results: {
            assessment: string;
            subject: string;
            type: string;
            obtained: number;
            total: number;
            evaluatedAt?: string;
            remarks?: string;
        }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Assessment Results</div>
            ${buildTable(
                ["Assessment", "Subject", "Type", "Score", "Evaluated", "Remarks"],
                results.map((r) => [
                    escapeHtml(r.assessment),
                    escapeHtml(r.subject),
                    escapeHtml(r.type),
                    escapeHtml(`${r.obtained} / ${r.total}`),
                    escapeHtml(formatDate(r.evaluatedAt)),
                    escapeHtml(r.remarks || "—"),
                ])
            )}
          </div>
        `;

        return buildDocument(
            "Performance Report",
            studentName,
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    attendanceSheet: ({
        title,
        className,
        subject,
        teacher,
        date,
        records,
    }: {
        title: string;
        className: string;
        subject: string;
        teacher: string;
        date: string;
        records: { name: string; rollNumber?: string; status: string }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Session Details</div>
            <div class="card-row">
              <div class="stat-card"><div class="stat-value">${escapeHtml(className)}</div><div class="stat-label">Class</div></div>
              <div class="stat-card"><div class="stat-value">${escapeHtml(subject)}</div><div class="stat-label">Subject</div></div>
              <div class="stat-card"><div class="stat-value">${escapeHtml(formatDate(date))}</div><div class="stat-label">Date</div></div>
            </div>
          </div>
          <div class="section">
            <div class="section-title">Student Attendance</div>
            ${buildTable(
                ["Student", "Roll No", "Status"],
                records.map((r) => [
                    escapeHtml(r.name),
                    escapeHtml(r.rollNumber || "—"),
                    statusBadge(r.status),
                ])
            )}
          </div>
        `;

        return buildDocument(
            title,
            teacher,
            {
                "Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    gradeSheet: ({
        title,
        className,
        subject,
        maxMarks,
        date,
        records,
    }: {
        title: string;
        className: string;
        subject: string;
        maxMarks: number;
        date?: string;
        records: { name: string; rollNumber?: string; obtained: number; remarks?: string }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Assessment Details</div>
            <div class="card-row">
              <div class="stat-card"><div class="stat-value">${escapeHtml(className)}</div><div class="stat-label">Class</div></div>
              <div class="stat-card"><div class="stat-value">${escapeHtml(subject)}</div><div class="stat-label">Subject</div></div>
              <div class="stat-card"><div class="stat-value">${maxMarks}</div><div class="stat-label">Max Marks</div></div>
            </div>
          </div>
          <div class="section">
            <div class="section-title">Student Scores</div>
            ${buildTable(
                ["Student", "Roll No", "Score", "Remarks"],
                records.map((r) => [
                    escapeHtml(r.name),
                    escapeHtml(r.rollNumber || "—"),
                    escapeHtml(`${r.obtained} / ${maxMarks}`),
                    escapeHtml(r.remarks || "—"),
                ])
            )}
          </div>
        `;

        return buildDocument(
            title,
            date ? `Assessment Date: ${formatDate(date)}` : "Assessment Grade Sheet",
            {
                "Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    studentPerformanceReport: ({
        studentName,
        institutionName,
        stats,
        results,
    }: {
        studentName: string;
        institutionName?: string;
        stats: { averageScore: string; totalAssessments: number };
        results: { assessment: string; subject: string; obtained: number; total: number; remarks?: string }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Performance Summary</div>
            <div class="card-row">
              <div class="stat-card"><div class="stat-value">${escapeHtml(stats.averageScore)}</div><div class="stat-label">Average Score</div></div>
              <div class="stat-card"><div class="stat-value">${stats.totalAssessments}</div><div class="stat-label">Assessments</div></div>
            </div>
          </div>
          <div class="section">
            <div class="section-title">Assessment Breakdown</div>
            ${buildTable(
                ["Assessment", "Subject", "Score", "Remarks"],
                results.map((r) => [
                    escapeHtml(r.assessment),
                    escapeHtml(r.subject),
                    escapeHtml(`${r.obtained} / ${r.total}`),
                    escapeHtml(r.remarks || "—"),
                ])
            )}
          </div>
        `;

        return buildDocument(
            "Student Performance Report",
            studentName,
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    leaveRegister: ({
        title,
        institutionName,
        rows,
    }: {
        title: string;
        institutionName?: string;
        rows: { teacher: string; type: string; range: string; days: number; status: string; reason: string }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Leave Records</div>
            ${buildTable(
                ["Teacher", "Type", "Date Range", "Days", "Status", "Reason"],
                rows.map((r) => [
                    escapeHtml(r.teacher),
                    escapeHtml(r.type),
                    escapeHtml(r.range),
                    escapeHtml(String(r.days)),
                    statusBadge(r.status),
                    escapeHtml(r.reason || "—"),
                ])
            )}
          </div>
        `;

        return buildDocument(
            title,
            "Leave Register",
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    teacherActivityReport: ({
        teacherName,
        institutionName,
        summary,
        attendanceRows,
        assessmentRows,
    }: {
        teacherName: string;
        institutionName?: string;
        summary: { totalClasses: number; attendanceSessions: number; assessments: number };
        attendanceRows: { date: string; className: string; subject: string }[];
        assessmentRows: { title: string; subject: string; className: string }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Activity Summary</div>
            <div class="card-row">
              <div class="stat-card"><div class="stat-value">${summary.totalClasses}</div><div class="stat-label">Classes Assigned</div></div>
              <div class="stat-card"><div class="stat-value">${summary.attendanceSessions}</div><div class="stat-label">Attendance Sessions</div></div>
              <div class="stat-card"><div class="stat-value">${summary.assessments}</div><div class="stat-label">Assessments</div></div>
            </div>
          </div>
          <div class="section">
            <div class="section-title">Attendance Sessions</div>
            ${buildTable(
                ["Date", "Class", "Subject"],
                attendanceRows.map((r) => [
                    escapeHtml(formatDate(r.date)),
                    escapeHtml(r.className),
                    escapeHtml(r.subject),
                ])
            )}
          </div>
          <div class="section">
            <div class="section-title">Assessments</div>
            ${buildTable(
                ["Assessment", "Subject", "Class"],
                assessmentRows.map((r) => [
                    escapeHtml(r.title),
                    escapeHtml(r.subject),
                    escapeHtml(r.className),
                ])
            )}
          </div>
        `;

        return buildDocument(
            "Teacher Activity Report",
            teacherName,
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },

    allStudentsPerformance: ({
        institutionName,
        rows,
    }: {
        institutionName?: string;
        rows: { name: string; rollNumber?: string; className?: string; avgScore: number; totalAssessments: number }[];
    }) => {
        const content = `
          <div class="section">
            <div class="section-title">Student Performance Summary</div>
            ${buildTable(
                ["Student", "Roll No", "Class", "Avg Score", "Assessments"],
                rows.map((r) => [
                    escapeHtml(r.name),
                    escapeHtml(r.rollNumber || "—"),
                    escapeHtml(r.className || "—"),
                    escapeHtml(formatPercent(r.avgScore)),
                    escapeHtml(String(r.totalAssessments)),
                ])
            )}
          </div>
        `;

        return buildDocument(
            "All Students Performance",
            "Institution-wide summary",
            {
                Institution: institutionName || "",
                "Report Generated": formatDateTime(new Date().toISOString()),
            },
            content
        );
    },
};
