export const APPWRITE_PROJECT_ID = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID || '';
export const APPWRITE_PROJECT_NAME = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_NAME || '';
export const APPWRITE_ENDPOINT = process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT || '';
export const APPWRITE_DATABASE_ID = process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID || '';
export const APPWRITE_STORAGE_ID = process.env.EXPO_PUBLIC_APPWRITE_STORAGE_ID || '';
