import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import {
  ActivityIndicator,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  Text,
  TextInput,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View
} from "react-native";
import { ID } from "react-native-appwrite";

import { account } from "../../services/appwrite/client";
import { COLLECTIONS } from "../../services/appwrite/collections";
import { databaseService } from "../../services/appwrite/database.service";
import { institutionService } from "../../services/institution.service";
import { useAuth } from "../../store/hooks/useAuth";
import { useTheme } from "../../store/hooks/useTheme";

const Signup = () => {
  const { login } = useAuth();
  const { isDark } = useTheme();
  const router = useRouter();

  const [step, setStep] = useState<1 | 2>(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Form State
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);

  const [instituteName, setInstituteName] = useState("");
  const [instituteCode, setInstituteCode] = useState("");

  const handleNext = () => {
    setError("");
    if (!name || !email || !password) {
      setError("Please fill in all fields");
      return;
    }
    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email.trim())) {
      setError("Please enter a valid email address");
      return;
    }
    setStep(2);
  };

  const handleBack = () => {
    setError("");
    setStep(1);
  };

  const handleSignup = async () => {
    setError("");
    if (!instituteName || !instituteCode) {
      setError("Please fill in all institute fields");
      return;
    }

    setLoading(true);

    let createdAccountId = null;
    let createdInstitutionId = null;

    try {
      // Step 1: Create Auth Account
      const userAccount = await account.create(
        ID.unique(),
        email.trim(),
        password,
        name
      );
      createdAccountId = userAccount.$id;

      // Step 2: Create Institute
      const institutionData = {
        name: instituteName.trim(),
        code: instituteCode.trim(),
        isActive: true,
      };
      // @ts-ignore - ID is auto-generated by createDocument if passed as 'unique()', but our service create method wraps it.
      // Actually existing service creates document with ID.unique() inside.
      const institution = await institutionService.create(institutionData);
      createdInstitutionId = institution.$id;

      // Step 3: Create User Record (Associate with Institute + Role = ADMIN)
      await databaseService.createUserDocument(COLLECTIONS.USERS, userAccount.$id, {
        userId: userAccount.$id,
        email: email.trim(),
        name: name.trim(),
        role: "ADMIN",
        institution: institution.$id,
        isActive: true,
      });

      // Step 4: Login (Auth Service) - This will update global state via useAuth
      await login(email.trim(), password, "teacher");

      // Step 5: Redirect (Handled by Layout/Router usually, but explicit here for safety)
      router.replace("/(admin)/dashboard");

    } catch (err: any) {
      console.error("Signup Flow Error:", err);
      // Attempt generic cleanup if possible (User deletion is only possible if logged in usually, or via server function)
      // Since we are client side, we might be limited.
      // If we failed at login, account exists.

      let msg = err.message || "An unexpected error occurred during signup.";
      if (msg.includes("already exists")) {
        msg = "Account or Institute code already exists.";
      }
      setError(msg);

      // If we created account but failed later, we might leave a ghost account. 
      // Handling this strictly on client is hard without a server function. 
      // We will show error and ask user to try again (or contact support).
    } finally {
      setLoading(false);
    }
  };

  const content = (
    <View className="flex-1 justify-center px-6 w-full max-w-sm md:max-w-md self-center">

      {/* Header */}
      <View className="mb-8">
        <Text className="text-3xl font-bold text-center text-primary dark:text-dark-primary mb-2">
          {step === 1 ? "Create Account" : "Institute Details"}
        </Text>
        <Text className="text-center text-textSecondary dark:text-dark-textSecondary">
          {step === 1 ? "Step 1 of 2: Personal Details" : "Step 2 of 2: Setup your Institute"}
        </Text>
      </View>

      {/* Form Fields */}
      {step === 1 ? (
        <>
          <TextInput
            placeholder="Full Name"
            className="bg-card dark:bg-dark-card border border-border dark:border-dark-border rounded-xl px-4 py-4 mb-4 text-textPrimary dark:text-dark-textPrimary"
            value={name}
            placeholderTextColor={isDark ? "#9CA3AF" : "#94A3B8"}
            onChangeText={(v) => { setName(v); setError(""); }}
          />

          <TextInput
            placeholder="Email"
            className="bg-card dark:bg-dark-card border border-border dark:border-dark-border rounded-xl px-4 py-4 mb-4 text-textPrimary dark:text-dark-textPrimary"
            value={email}
            placeholderTextColor={isDark ? "#9CA3AF" : "#94A3B8"}
            onChangeText={(v) => { setEmail(v); setError(""); }}
            autoCapitalize="none"
            keyboardType="email-address"
          />

          <View className="relative mb-4">
            <TextInput
              placeholder="Password"
              secureTextEntry={!showPassword}
              className="bg-card dark:bg-dark-card border border-border dark:border-dark-border rounded-xl px-4 py-4 text-textPrimary dark:text-dark-textPrimary pr-12"
              value={password}
              placeholderTextColor={isDark ? "#9CA3AF" : "#94A3B8"}
              onChangeText={(v) => { setPassword(v); setError(""); }}
            />
            <TouchableOpacity
              onPress={() => setShowPassword(!showPassword)}
              className="absolute right-4 top-4"
              testID="toggle-password"
            >
              <Ionicons
                name={showPassword ? "eye-off" : "eye"}
                size={24}
                color={isDark ? "#9CA3AF" : "#94A3B8"}
              />
            </TouchableOpacity>
          </View>
        </>
      ) : (
        <>
          <TextInput
            placeholder="Institute Name"
            className="bg-card dark:bg-dark-card border border-border dark:border-dark-border rounded-xl px-4 py-4 mb-4 text-textPrimary dark:text-dark-textPrimary"
            value={instituteName}
            placeholderTextColor={isDark ? "#9CA3AF" : "#94A3B8"}
            onChangeText={(v) => { setInstituteName(v); setError(""); }}
          />

          <TextInput
            placeholder="Institute Code (e.g. SCH001)"
            className="bg-card dark:bg-dark-card border border-border dark:border-dark-border rounded-xl px-4 py-4 mb-4 text-textPrimary dark:text-dark-textPrimary"
            value={instituteCode}
            placeholderTextColor={isDark ? "#9CA3AF" : "#94A3B8"}
            onChangeText={(v) => { setInstituteCode(v); setError(""); }}
            autoCapitalize="characters"
          />
          <Text className="text-xs text-muted dark:text-dark-muted mb-4 px-1">
            This code will be used to identify your institute.
          </Text>
        </>
      )}

      {/* Error Message */}
      {error ? <Text className="text-error text-center mb-4">{error}</Text> : null}

      {/* Action Buttons */}
      <View className="mt-4">
        {step === 1 ? (
          <TouchableOpacity
            onPress={handleNext}
            className="bg-primary dark:bg-dark-primary rounded-xl py-4 items-center"
          >
            <Text className="text-white font-semibold text-lg">Next</Text>
          </TouchableOpacity>
        ) : (
          <View className="flex-col gap-3">
            <TouchableOpacity
              onPress={handleSignup}
              disabled={loading}
              className="bg-primary dark:bg-dark-primary rounded-xl py-4 items-center"
            >
              {loading ? (
                <ActivityIndicator color="#fff" />
              ) : (
                <Text className="text-white font-semibold text-lg">Create Account</Text>
              )}
            </TouchableOpacity>

            {!loading && (
              <TouchableOpacity
                onPress={handleBack}
                className="bg-transparent border border-border dark:border-dark-border rounded-xl py-4 items-center"
              >
                <Text className="text-textPrimary dark:text-dark-textPrimary font-semibold text-lg">Back</Text>
              </TouchableOpacity>
            )}
          </View>
        )}
      </View>

      {step === 1 && (
        <View className="flex-row justify-center mt-6">
          <Text className="text-textSecondary dark:text-dark-textSecondary">
            Already have an account?{" "}
          </Text>
          <TouchableOpacity onPress={() => router.push("/(auth)/login")}>
            <Text className="text-primary dark:text-dark-primary font-semibold">
              Login
            </Text>
          </TouchableOpacity>
        </View>
      )}

    </View>
  )

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
      className="flex-1 bg-background dark:bg-dark-background"
    >
      {Platform.OS === "web" ? content : (
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          {content}
        </TouchableWithoutFeedback>
      )}
    </KeyboardAvoidingView>
  );
};

export default Signup;
